remove unused stropts.h
This is not present on some toolchains / platforms and
kills build.  It does not seem to be used either.

In file included from lib/list.c:34:
../src/include/std_internal.h:49:10: fatal error: stropts.h: No such file or directory
 #include <stropts.h>
          ^~~~~~~~~~~

Signed-off-by: Andy Green <andy@warmcat.com>